# Copyright (C) 2010, Redbeard Enterprises Ltd.
#
# Not to be used in any form without express written consent.
# All rights reserved.
#
# $Id: makefile 2 2010-03-29 03:41:56Z jason $

RUMPATH := ../redrum

STATICLIBS := ewplasma  \
              ewcrypt

# define module directories to source objects from when building
# the above libs
ewplasma := src/plasma
ewcrypt  := src/crypt

include $(RUMPATH)/target.mk
include $(RUMPATH)/lib.mk
