# Copyright (C) 2015, Redbeard Enterprises Ltd.
#
# Not to be used in any form without express written consent.
# All rights reserved.

RUMPATH := ../redrum

STATICLIBS := eyewarp

# define module directories to source objects from when building
# the above libs
eyewarp := src/common src/curve src/filter src/fractal src/crypto

include $(RUMPATH)/target.mk
include $(RUMPATH)/lib.mk
