# Copyright (C) 2015, Redbeard Enterprises Ltd.
#
# Not to be used in any form without express written consent.
# All rights reserved.
#
# $Id: makefile 2 2010-03-29 03:41:56Z jason $

LIBS := eyewarp avformat avcodec avresample avutil swresample swscale m z pthread

include ../app.mk
